import {
  INTEGRATION_STATUSES,
  INTEGRATION_TYPES,
  type IntegrationRegistryItem
} from './integration-registry.types'

const miyopDeveloper = 'MIYOP'
const version = '1.0.0'

export const INTEGRATION_REGISTRY: IntegrationRegistryItem[] = [
  {
    integrationId: 'integration-whatsapp',
    code: 'whatsapp',
    name: 'WhatsApp',
    icon: 'WA',
    description: 'Müşteri iletişimi ve operasyon bildirimleri için mesajlaşma entegrasyonu yuvası.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.COMMUNICATION,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['OAUTH', 'WEBHOOK'],
    webhookReady: true,
    marketplaceVisible: false,
    displayOrder: 10,
    tags: ['communication', 'message', 'customer']
  },
  {
    integrationId: 'integration-email',
    code: 'email',
    name: 'E-Posta',
    icon: 'EM',
    description: 'Sistem bildirimleri ve dış iletişim e-postaları için sağlayıcı bağlantı altyapısı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.COMMUNICATION,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['API_KEY', 'WEBHOOK'],
    webhookReady: true,
    marketplaceVisible: false,
    displayOrder: 20,
    tags: ['communication', 'mail', 'notification']
  },
  {
    integrationId: 'integration-sms',
    code: 'sms',
    name: 'SMS',
    icon: 'SM',
    description: 'Kısa mesaj bildirimleri için sağlayıcıdan bağımsız entegrasyon alanı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.NOTIFICATION,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['API_KEY'],
    webhookReady: false,
    marketplaceVisible: false,
    displayOrder: 30,
    tags: ['sms', 'notification', 'message']
  },
  {
    integrationId: 'integration-ai',
    code: 'ai-provider',
    name: 'Yapay Zeka',
    icon: 'AI',
    description: 'Platform asistanı, öneriler ve otomasyonlar için sağlayıcıdan bağımsız AI bağlantı yuvası.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.AI,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['API_KEY'],
    webhookReady: false,
    marketplaceVisible: false,
    displayOrder: 40,
    tags: ['ai', 'assistant', 'recommendation']
  },
  {
    integrationId: 'integration-cloud-storage',
    code: 'cloud-storage',
    name: 'Bulut Depolama',
    icon: 'BD',
    description: 'Yedekleme, dosya saklama ve belge arşivi için depolama sağlayıcı altyapısı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.STORAGE,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['OAUTH', 'API_KEY'],
    webhookReady: false,
    marketplaceVisible: false,
    displayOrder: 50,
    tags: ['storage', 'backup', 'document']
  },
  {
    integrationId: 'integration-printer',
    code: 'printer',
    name: 'Yazıcı',
    icon: 'YZ',
    description: 'Fiş, üretim çıktısı ve operasyon yazıcıları için cihaz bağlantı altyapısı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.HARDWARE,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['DEVICE_PAIRING'],
    webhookReady: false,
    marketplaceVisible: false,
    displayOrder: 60,
    tags: ['hardware', 'device', 'print']
  },
  {
    integrationId: 'integration-barcode-reader',
    code: 'barcode-reader',
    name: 'Barkod Okuyucu',
    icon: 'BO',
    description: 'Stok, ürün ve operasyon hareketleri için cihaz eşleştirme altyapısı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.HARDWARE,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['DEVICE_PAIRING'],
    webhookReady: false,
    marketplaceVisible: false,
    displayOrder: 70,
    tags: ['hardware', 'barcode', 'device']
  },
  {
    integrationId: 'integration-pos',
    code: 'pos',
    name: 'POS',
    icon: 'PS',
    description: 'Ödeme terminalleri ve tahsilat sağlayıcıları için ödeme entegrasyonu altyapısı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.PAYMENT,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['API_KEY', 'DEVICE_PAIRING'],
    webhookReady: true,
    marketplaceVisible: false,
    displayOrder: 80,
    tags: ['payment', 'pos', 'terminal']
  },
  {
    integrationId: 'integration-e-invoice',
    code: 'e-invoice',
    name: 'e-Fatura',
    icon: 'EF',
    description: 'Elektronik fatura servisleri için belge ve muhasebe entegrasyonu altyapısı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.ACCOUNTING,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['API_KEY'],
    webhookReady: true,
    marketplaceVisible: false,
    displayOrder: 90,
    tags: ['accounting', 'invoice', 'document']
  },
  {
    integrationId: 'integration-e-archive',
    code: 'e-archive',
    name: 'e-Arşiv',
    icon: 'EA',
    description: 'Elektronik arşiv belge akışları için sağlayıcıdan bağımsız entegrasyon alanı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.ACCOUNTING,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['API_KEY'],
    webhookReady: true,
    marketplaceVisible: false,
    displayOrder: 100,
    tags: ['accounting', 'archive', 'document']
  },
  {
    integrationId: 'integration-logo',
    code: 'logo',
    name: 'Logo',
    icon: 'LG',
    description: 'Muhasebe ve ERP senkronizasyonları için Logo bağlantı yuvası.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.ACCOUNTING,
    version,
    status: INTEGRATION_STATUSES.COMING_SOON,
    authMethods: ['API_KEY'],
    webhookReady: false,
    marketplaceVisible: false,
    displayOrder: 110,
    tags: ['accounting', 'erp']
  },
  {
    integrationId: 'integration-mikro',
    code: 'mikro',
    name: 'Mikro',
    icon: 'MK',
    description: 'Muhasebe ve ERP veri akışı için Mikro bağlantı altyapısı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.ACCOUNTING,
    version,
    status: INTEGRATION_STATUSES.COMING_SOON,
    authMethods: ['API_KEY'],
    webhookReady: false,
    marketplaceVisible: false,
    displayOrder: 120,
    tags: ['accounting', 'erp']
  },
  {
    integrationId: 'integration-nebim',
    code: 'nebim',
    name: 'Nebim',
    icon: 'NB',
    description: 'Perakende ve ERP senaryoları için Nebim bağlantı altyapısı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.ACCOUNTING,
    version,
    status: INTEGRATION_STATUSES.COMING_SOON,
    authMethods: ['API_KEY'],
    webhookReady: false,
    marketplaceVisible: false,
    displayOrder: 130,
    tags: ['accounting', 'retail', 'erp']
  },
  {
    integrationId: 'integration-parasut',
    code: 'parasut',
    name: 'Paraşüt',
    icon: 'PR',
    description: 'Finans ve muhasebe kayıtları için Paraşüt bağlantı yuvası.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.ACCOUNTING,
    version,
    status: INTEGRATION_STATUSES.COMING_SOON,
    authMethods: ['OAUTH', 'API_KEY'],
    webhookReady: true,
    marketplaceVisible: false,
    displayOrder: 140,
    tags: ['accounting', 'finance']
  },
  {
    integrationId: 'integration-google-calendar',
    code: 'google-calendar',
    name: 'Google Takvim',
    icon: 'GT',
    description: 'Randevu, planlama ve operasyon takvimi için üretkenlik entegrasyonu yuvası.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.PRODUCTIVITY,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['OAUTH', 'WEBHOOK'],
    webhookReady: true,
    marketplaceVisible: false,
    displayOrder: 150,
    tags: ['calendar', 'productivity', 'planning']
  },
  {
    integrationId: 'integration-outlook-calendar',
    code: 'outlook-calendar',
    name: 'Outlook',
    icon: 'OL',
    description: 'Takvim, e-posta ve planlama akışları için üretkenlik entegrasyonu altyapısı.',
    developer: miyopDeveloper,
    category: INTEGRATION_TYPES.PRODUCTIVITY,
    version,
    status: INTEGRATION_STATUSES.AVAILABLE,
    authMethods: ['OAUTH', 'WEBHOOK'],
    webhookReady: true,
    marketplaceVisible: false,
    displayOrder: 160,
    tags: ['calendar', 'productivity', 'planning']
  }
]

export const getIntegrationRegistry = () => {
  return [...INTEGRATION_REGISTRY]
    .sort((first, second) => first.displayOrder - second.displayOrder)
}
